### PR TITLE
Add store function

### PR DESCRIPTION
**Pull request by sibasish14**
Add store() to store user info in a csv file.
Screenshots : 
screenshot from 2017-12-20 00-05-08
screenshot from 2017-12-20 00-05-50

Closes https://github.com/palash25/CoWaPS/issues/6

### CODE REVIEW

**Comment by palash25** [comment]
This message was posted by [GitMate.io](https://gitmate.io) with timestamp signature `:1eRY5S:rTnUS6J6CtwdmVuwoJo81GFwbbg`

**Comment by sibasish14** [comment]
@palash25 I think this should work.

**Comment by sibasish14** [comment]
Thanks @palash25 :)

**Comment by palash25** [comment]
@sibasish14 No need to comment on closed/merged threads, it shows up in my notifications :wink:

**Pull request merged**
