### PR TITLE
Add Installation in README.md

### PR DESCRIPTION
**Pull request by sibasish14**
Closes https://github.com/palash25/CoWaPS/issues/12

### CODE REVIEW

**Comment by palash25** [comment]
(Powered by [GitMate.io](https://gitmate.io))

**Comment by sibasish14** [comment]
@palash25 please have a look.

**Comment by palash25** [comment]
Can you add a section about installing using virtualenv too?

**Comment by sibasish14** [comment]
@palash25 please check now.

**Comment by palash25** [comment]
Nice :+1:

**Pull request merged**
